// массив флагов Ы
let flags = [
    { image: 'img/ad.png', country: 'Андорра' },
    { image: 'img/ae.png', country: 'Объединённые Арабские Эмираты' },
    { image: 'img/af.png', country: 'Афганистан' },
    { image: 'img/ag.png', country: 'Антигуа и Барбуда' },
    { image: 'img/ai.png', country: 'Ангилья' },
    { image: 'img/al.png', country: 'Албания' },
    { image: 'img/am.png', country: 'Армения' },
    { image: 'img/ao.png', country: 'Ангола' },
    { image: 'img/aq.png', country: 'Антарктида' },
    { image: 'img/ar.png', country: 'Аргентина' },
    { image: 'img/as.png', country: 'Американское Самоа' },
    { image: 'img/at.png', country: 'Австрия' },
    { image: 'img/au.png', country: 'Австралия' },
    { image: 'img/aw.png', country: 'Аруба' },
    { image: 'img/ax.png', country: 'Аландские острова' },
    { image: 'img/az.png', country: 'Азербайджан' },
    { image: 'img/ba.png', country: 'Босния и Герцеговина' },
    { image: 'img/bb.png', country: 'Барбадос' },
    { image: 'img/bd.png', country: 'Бангладеш' },
    { image: 'img/be.png', country: 'Бельгия' },
    { image: 'img/bf.png', country: 'Буркина-Фасо' },
    { image: 'img/bg.png', country: 'Болгария' },
    { image: 'img/bh.png', country: 'Бахрейн' },
    { image: 'img/bi.png', country: 'Бурунди' },
    { image: 'img/bj.png', country: 'Бенин' },
    { image: 'img/bl.png', country: 'Сен-Бартелеми' },
    { image: 'img/bm.png', country: 'Бермудские острова' },
    { image: 'img/bn.png', country: 'Бруней' },
    { image: 'img/bo.png', country: 'Боливия' },
    { image: 'img/bq.png', country: 'Бонэйр, Синт-Эстатиус и Саба' },
    { image: 'img/br.png', country: 'Бразилия' },
    { image: 'img/bs.png', country: 'Багамские Острова' },
    { image: 'img/bt.png', country: 'Бутан' },
    { image: 'img/bv.png', country: 'Остров Буве' },
    { image: 'img/bw.png', country: 'Ботсвана' },
    { image: 'img/by.png', country: 'Беларусь' },
    { image: 'img/bz.png', country: 'Белиз' },
    { image: 'img/ca.png', country: 'Канада' },
    { image: 'img/cc.png', country: 'Кокосовые (Килинг) острова' },
    { image: 'img/cd.png', country: 'Конго (Демократическая Республика)' },
    { image: 'img/cf.png', country: 'Центральноафриканская Республика' },
    { image: 'img/cg.png', country: 'Конго' },
    { image: 'img/ch.png', country: 'Швейцария' },
    { image: 'img/ci.png', country: 'Кот-д’Ивуар' },
    { image: 'img/ck.png', country: 'Острова Кука' },
    { image: 'img/cl.png', country: 'Чили' },
    { image: 'img/cm.png', country: 'Камерун' },
    { image: 'img/cn.png', country: 'Китай' },
    { image: 'img/co.png', country: 'Колумбия' },
    { image: 'img/cr.png', country: 'Коста-Рика' },
    { image: 'img/cu.png', country: 'Куба' },
    { image: 'img/cv.png', country: 'Кабо-Верде' },
    { image: 'img/cw.png', country: 'Кюрасао' },
    { image: 'img/cx.png', country: 'Остров Рождества' },
    { image: 'img/cy.png', country: 'Кипр' },
    { image: 'img/cz.png', country: 'Чехия' },
    { image: 'img/de.png', country: 'Германия' },
    { image: 'img/dj.png', country: 'Джибути' },
    { image: 'img/dk.png', country: 'Дания' },
    { image: 'img/dm.png', country: 'Доминика' },
    { image: 'img/do.png', country: 'Доминиканская Республика' },
    { image: 'img/dz.png', country: 'Алжир' },
    { image: 'img/ec.png', country: 'Эквадор' },
    { image: 'img/ee.png', country: 'Эстония' },
    { image: 'img/eg.png', country: 'Египет' },
    { image: 'img/eh.png', country: 'Западная Сахара' },
    { image: 'img/er.png', country: 'Эритрея' },
    { image: 'img/es.png', country: 'Испания' },
    { image: 'img/et.png', country: 'Эфиопия' },
    { image: 'img/fi.png', country: 'Финляндия' },
    { image: 'img/fj.png', country: 'Фиджи' },
    { image: 'img/fk.png', country: 'Фолклендские острова' },
    { image: 'img/fm.png', country: 'Микронезия' },
    { image: 'img/fo.png', country: 'Фарерские острова' },
    { image: 'img/fr.png', country: 'Франция' },
    { image: 'img/ga.png', country: 'Габон' },
    { image: 'img/gb.png', country: 'Великобритания' },
    { image: 'img/gb-eng.png', country: 'Англия' },
    { image: 'img/gb-nir.png', country: 'Северная Ирландия' },
    { image: 'img/gb-sct.png', country: 'Шотландия' },
    { image: 'img/gb-wls.png', country: 'Уэльс' },
    { image: 'img/gd.png', country: 'Гренада' },
    { image: 'img/ge.png', country: 'Грузия' },
    { image: 'img/gf.png', country: 'Французская Гвиана' },
    { image: 'img/gg.png', country: 'Гернси' },
    { image: 'img/gh.png', country: 'Гана' },
    { image: 'img/gi.png', country: 'Гибралтар' },
    { image: 'img/gl.png', country: 'Гренландия' },
    { image: 'img/gm.png', country: 'Гамбия' },
    { image: 'img/gn.png', country: 'Гвинея' },
    { image: 'img/gp.png', country: 'Гваделупа' },
    { image: 'img/gq.png', country: 'Экваториальная Гвинея' },
    { image: 'img/gr.png', country: 'Греция' },
    { image: 'img/gs.png', country: 'Южная Георгия и Южные Сандвичевы острова' },
    { image: 'img/gt.png', country: 'Гватемала' },
    { image: 'img/gu.png', country: 'Гуам' },
    { image: 'img/gw.png', country: 'Гвинея-Бисау' },
    { image: 'img/gy.png', country: 'Гайана' },
    { image: 'img/hk.png', country: 'Гонконг' },
    { image: 'img/hm.png', country: 'Остров Херд и острова Макдональд' },
    { image: 'img/hn.png', country: 'Гондурас' },
    { image: 'img/hr.png', country: 'Хорватия' },
    { image: 'img/ht.png', country: 'Гаити' },
    { image: 'img/hu.png', country: 'Венгрия' },
    { image: 'img/id.png', country: 'Индонезия' },
    { image: 'img/ie.png', country: 'Ирландия' },
    { image: 'img/il.png', country: 'Израиль' },
    { image: 'img/im.png', country: 'Остров Мэн' },
    { image: 'img/in.png', country: 'Индия' },
    { image: 'img/io.png', country: 'Британская территория в Индийском океане' },
    { image: 'img/iq.png', country: 'Ирак' },
    { image: 'img/ir.png', country: 'Иран' },
    { image: 'img/is.png', country: 'Исландия' },
    { image: 'img/it.png', country: 'Италия' },
    { image: 'img/je.png', country: 'Джерси' },
    { image: 'img/jm.png', country: 'Ямайка' },
    { image: 'img/jo.png', country: 'Иордания' },
    { image: 'img/jp.png', country: 'Япония' },
    { image: 'img/ke.png', country: 'Кения' },
    { image: 'img/kg.png', country: 'Киргизия' },
    { image: 'img/kh.png', country: 'Камбоджа' },
    { image: 'img/ki.png', country: 'Кирибати' },
    { image: 'img/km.png', country: 'Коморы' },
    { image: 'img/kn.png', country: 'Сент-Китс и Невис' },
    { image: 'img/kp.png', country: 'Северная Корея' },
    { image: 'img/kr.png', country: 'Южная Корея' },
    { image: 'img/kw.png', country: 'Кувейт' },
    { image: 'img/ky.png', country: 'Каймановы острова' },
    { image: 'img/kz.png', country: 'Казахстан' },
    { image: 'img/la.png', country: 'Лаос' },
    { image: 'img/lb.png', country: 'Ливан' },
    { image: 'img/lc.png', country: 'Сент-Люсия' },
    { image: 'img/li.png', country: 'Лихтенштейн' },
    { image: 'img/lk.png', country: 'Шри-Ланка' },
    { image: 'img/lr.png', country: 'Либерия' },
    { image: 'img/ls.png', country: 'Лесото' },
    { image: 'img/lt.png', country: 'Литва' },
    { image: 'img/lu.png', country: 'Люксембург' },
    { image: 'img/lv.png', country: 'Латвия' },
    { image: 'img/ly.png', country: 'Ливия' },
    { image: 'img/ma.png', country: 'Марокко' },
    { image: 'img/mc.png', country: 'Монако' },
    { image: 'img/md.png', country: 'Молдова' },
    { image: 'img/me.png', country: 'Черногория' },
    { image: 'img/mf.png', country: 'Сен-Мартен' },
    { image: 'img/mg.png', country: 'Мадагаскар' },
    { image: 'img/mh.png', country: 'Маршалловы Острова' },
    { image: 'img/mk.png', country: 'Северная Македония' },
    { image: 'img/ml.png', country: 'Мали' },
    { image: 'img/mm.png', country: 'Мьянма' },
    { image: 'img/mn.png', country: 'Монголия' },
    { image: 'img/mo.png', country: 'Макао' },
    { image: 'img/mp.png', country: 'Северные Марианские острова' },
    { image: 'img/mq.png', country: 'Мартиника' },
    { image: 'img/mr.png', country: 'Мавритания' },
    { image: 'img/ms.png', country: 'Монтсеррат' },
    { image: 'img/mt.png', country: 'Мальта' },
    { image: 'img/mu.png', country: 'Маврикий' },
    { image: 'img/mv.png', country: 'Мальдивы' },
    { image: 'img/mw.png', country: 'Малави' },
    { image: 'img/mx.png', country: 'Мексика' },
    { image: 'img/my.png', country: 'Малайзия' },
    { image: 'img/mz.png', country: 'Мозамбик' },
    { image: 'img/na.png', country: 'Намибия' },
    { image: 'img/nc.png', country: 'Новая Каледония' },
    { image: 'img/ne.png', country: 'Нигер' },
    { image: 'img/nf.png', country: 'Остров Норфолк' },
    { image: 'img/ng.png', country: 'Нигерия' },
    { image: 'img/ni.png', country: 'Никарагуа' },
    { image: 'img/nl.png', country: 'Нидерланды' },
    { image: 'img/no.png', country: 'Норвегия' },
    { image: 'img/np.png', country: 'Непал' },
    { image: 'img/nr.png', country: 'Науру' },
    { image: 'img/nu.png', country: 'Ниуэ' },
    { image: 'img/nz.png', country: 'Новая Зеландия' },
    { image: 'img/om.png', country: 'Оман' },
    { image: 'img/pa.png', country: 'Панама' },
    { image: 'img/pe.png', country: 'Перу' },
    { image: 'img/pf.png', country: 'Французская Полинезия' },
    { image: 'img/pg.png', country: 'Папуа - Новая Гвинея' },
    { image: 'img/ph.png', country: 'Филиппины' },
    { image: 'img/pk.png', country: 'Пакистан' },
    { image: 'img/pl.png', country: 'Польша' },
    { image: 'img/pm.png', country: 'Сен-Пьер и Микелон' },
    { image: 'img/pn.png', country: 'Питкэрн' },
    { image: 'img/pr.png', country: 'Пуэрто-Рико' },
    { image: 'img/ps.png', country: 'Палестина' },
    { image: 'img/pt.png', country: 'Португалия' },
    { image: 'img/pw.png', country: 'Палау' },
    { image: 'img/py.png', country: 'Парагвай' },
    { image: 'img/qa.png', country: 'Катар' },
    { image: 'img/re.png', country: 'Реюньон' },
    { image: 'img/ro.png', country: 'Румыния' },
    { image: 'img/rs.png', country: 'Сербия' },
    { image: 'img/ru.png', country: 'Россия' },
    { image: 'img/rw.png', country: 'Руанда' },
    { image: 'img/sa.png', country: 'Саудовская Аравия' },
    { image: 'img/sb.png', country: 'Соломоновы Острова' },
    { image: 'img/sc.png', country: 'Сейшельские острова' },
    { image: 'img/sd.png', country: 'Судан' },
    { image: 'img/se.png', country: 'Швеция' },
    { image: 'img/sg.png', country: 'Сингапур' },
    { image: 'img/sh.png', country: 'Остров Святой Елены' },
    { image: 'img/si.png', country: 'Словения' },
    { image: 'img/sj.png', country: 'Шпицберген и Ян-Майен' },
    { image: 'img/sk.png', country: 'Словакия' },
    { image: 'img/sl.png', country: 'Сьерра-Леоне' },
    { image: 'img/sm.png', country: 'Сан-Марино' },
    { image: 'img/sn.png', country: 'Сенегал' },
    { image: 'img/so.png', country: 'Сомали' },
    { image: 'img/sr.png', country: 'Суринам' },
    { image: 'img/ss.png', country: 'Южный Судан' },
    { image: 'img/st.png', country: 'Сан-Томе и Принсипи' },
    { image: 'img/sv.png', country: 'Сальвадор' },
    { image: 'img/sx.png', country: 'Синт-Мартен' },
    { image: 'img/sy.png', country: 'Сирия' },
    { image: 'img/sz.png', country: 'Эсватини' },
    { image: 'img/tc.png', country: 'Теркс и Кайкос' },
    { image: 'img/td.png', country: 'Чад' },
    { image: 'img/tf.png', country: 'Французские Южные и Антарктические территории' },
    { image: 'img/tg.png', country: 'Того' },
    { image: 'img/th.png', country: 'Таиланд' },
    { image: 'img/tj.png', country: 'Таджикистан' },
    { image: 'img/tk.png', country: 'Токелау' },
    { image: 'img/tl.png', country: 'Восточный Тимор' },
    { image: 'img/tm.png', country: 'Туркмения' },
    { image: 'img/tn.png', country: 'Тунис' },
    { image: 'img/to.png', country: 'Тонга' },
    { image: 'img/tr.png', country: 'Турция' },
    { image: 'img/tt.png', country: 'Тринидад и Тобаго' },
    { image: 'img/tv.png', country: 'Тувалу' },
    { image: 'img/tw.png', country: 'Тайвань' },
    { image: 'img/tz.png', country: 'Танзания' },
    { image: 'img/ua.png', country: 'Украина' },
    { image: 'img/ug.png', country: 'Уганда' },
    { image: 'img/um.png', country: 'Внешние малые острова США' },
    { image: 'img/us.png', country: 'Соединённые Штаты Америки' },
    { image: 'img/uy.png', country: 'Уругвай' },
    { image: 'img/uz.png', country: 'Узбекистан' },
    { image: 'img/va.png', country: 'Ватикан' },
    { image: 'img/vc.png', country: 'Сент-Винсент и Гренадины' },
    { image: 'img/ve.png', country: 'Венесуэла' },
    { image: 'img/vg.png', country: 'Британские Виргинские острова' },
    { image: 'img/vi.png', country: 'Американские Виргинские острова' },
    { image: 'img/vn.png', country: 'Вьетнам' },
    { image: 'img/vu.png', country: 'Вануату' },
    { image: 'img/wf.png', country: 'Уоллис и Футуна' },
    { image: 'img/ws.png', country: 'Самоа' },
    { image: 'img/xk.png', country: 'Косово' },
    { image: 'img/ye.png', country: 'Йемен' },
    { image: 'img/yt.png', country: 'Майотта' },
    { image: 'img/za.png', country: 'Южно-Африканская Республика' },
    { image: 'img/zm.png', country: 'Замбия' },
    { image: 'img/zw.png', country: 'Зимбабве' }
];

// Пул доступных цветов
const colors = ['#ef233c', '#e053ce', '#00a693', '#ffd506', '#0effd9', '#ce001b', '#008a00', '#61cdfb'];

let currentIndex = null;

// Функция для генерации случайного числа
function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomColor() {
    const index = getRandomInt(0, colors.length - 1);
    return colors.splice(index, 1)[0]; // Удаляем выбранный цвет из массива и возвращаем его
}

function generateFlag() {
    // Перемешиваем флаги, если все они были использованы
    if (flags.length === 0) {
        flags = [
    { image: 'img/ad.png', country: 'Андорра' },
    { image: 'img/ae.png', country: 'Объединённые Арабские Эмираты' },
    { image: 'img/af.png', country: 'Афганистан' },
    { image: 'img/ag.png', country: 'Антигуа и Барбуда' },
    { image: 'img/ai.png', country: 'Ангилья' },
    { image: 'img/al.png', country: 'Албания' },
    { image: 'img/am.png', country: 'Армения' },
    { image: 'img/ao.png', country: 'Ангола' },
    { image: 'img/aq.png', country: 'Антарктида' },
    { image: 'img/ar.png', country: 'Аргентина' },
    { image: 'img/as.png', country: 'Американское Самоа' },
    { image: 'img/at.png', country: 'Австрия' },
    { image: 'img/au.png', country: 'Австралия' },
    { image: 'img/aw.png', country: 'Аруба' },
    { image: 'img/ax.png', country: 'Аландские острова' },
    { image: 'img/az.png', country: 'Азербайджан' },
    { image: 'img/ba.png', country: 'Босния и Герцеговина' },
    { image: 'img/bb.png', country: 'Барбадос' },
    { image: 'img/bd.png', country: 'Бангладеш' },
    { image: 'img/be.png', country: 'Бельгия' },
    { image: 'img/bf.png', country: 'Буркина-Фасо' },
    { image: 'img/bg.png', country: 'Болгария' },
    { image: 'img/bh.png', country: 'Бахрейн' },
    { image: 'img/bi.png', country: 'Бурунди' },
    { image: 'img/bj.png', country: 'Бенин' },
    { image: 'img/bl.png', country: 'Сен-Бартелеми' },
    { image: 'img/bm.png', country: 'Бермудские острова' },
    { image: 'img/bn.png', country: 'Бруней' },
    { image: 'img/bo.png', country: 'Боливия' },
    { image: 'img/bq.png', country: 'Бонэйр, Синт-Эстатиус и Саба' },
    { image: 'img/br.png', country: 'Бразилия' },
    { image: 'img/bs.png', country: 'Багамские Острова' },
    { image: 'img/bt.png', country: 'Бутан' },
    { image: 'img/bv.png', country: 'Остров Буве' },
    { image: 'img/bw.png', country: 'Ботсвана' },
    { image: 'img/by.png', country: 'Беларусь' },
    { image: 'img/bz.png', country: 'Белиз' },
    { image: 'img/ca.png', country: 'Канада' },
    { image: 'img/cc.png', country: 'Кокосовые (Килинг) острова' },
    { image: 'img/cd.png', country: 'Конго (Демократическая Республика)' },
    { image: 'img/cf.png', country: 'Центральноафриканская Республика' },
    { image: 'img/cg.png', country: 'Конго' },
    { image: 'img/ch.png', country: 'Швейцария' },
    { image: 'img/ci.png', country: 'Кот-д’Ивуар' },
    { image: 'img/ck.png', country: 'Острова Кука' },
    { image: 'img/cl.png', country: 'Чили' },
    { image: 'img/cm.png', country: 'Камерун' },
    { image: 'img/cn.png', country: 'Китай' },
    { image: 'img/co.png', country: 'Колумбия' },
    { image: 'img/cr.png', country: 'Коста-Рика' },
    { image: 'img/cu.png', country: 'Куба' },
    { image: 'img/cv.png', country: 'Кабо-Верде' },
    { image: 'img/cw.png', country: 'Кюрасао' },
    { image: 'img/cx.png', country: 'Остров Рождества' },
    { image: 'img/cy.png', country: 'Кипр' },
    { image: 'img/cz.png', country: 'Чехия' },
    { image: 'img/de.png', country: 'Германия' },
    { image: 'img/dj.png', country: 'Джибути' },
    { image: 'img/dk.png', country: 'Дания' },
    { image: 'img/dm.png', country: 'Доминика' },
    { image: 'img/do.png', country: 'Доминиканская Республика' },
    { image: 'img/dz.png', country: 'Алжир' },
    { image: 'img/ec.png', country: 'Эквадор' },
    { image: 'img/ee.png', country: 'Эстония' },
    { image: 'img/eg.png', country: 'Египет' },
    { image: 'img/eh.png', country: 'Западная Сахара' },
    { image: 'img/er.png', country: 'Эритрея' },
    { image: 'img/es.png', country: 'Испания' },
    { image: 'img/et.png', country: 'Эфиопия' },
    { image: 'img/fi.png', country: 'Финляндия' },
    { image: 'img/fj.png', country: 'Фиджи' },
    { image: 'img/fk.png', country: 'Фолклендские острова' },
    { image: 'img/fm.png', country: 'Микронезия' },
    { image: 'img/fo.png', country: 'Фарерские острова' },
    { image: 'img/fr.png', country: 'Франция' },
    { image: 'img/ga.png', country: 'Габон' },
    { image: 'img/gb.png', country: 'Великобритания' },
    { image: 'img/gb-eng.png', country: 'Англия' },
    { image: 'img/gb-nir.png', country: 'Северная Ирландия' },
    { image: 'img/gb-sct.png', country: 'Шотландия' },
    { image: 'img/gb-wls.png', country: 'Уэльс' },
    { image: 'img/gd.png', country: 'Гренада' },
    { image: 'img/ge.png', country: 'Грузия' },
    { image: 'img/gf.png', country: 'Французская Гвиана' },
    { image: 'img/gg.png', country: 'Гернси' },
    { image: 'img/gh.png', country: 'Гана' },
    { image: 'img/gi.png', country: 'Гибралтар' },
    { image: 'img/gl.png', country: 'Гренландия' },
    { image: 'img/gm.png', country: 'Гамбия' },
    { image: 'img/gn.png', country: 'Гвинея' },
    { image: 'img/gp.png', country: 'Гваделупа' },
    { image: 'img/gq.png', country: 'Экваториальная Гвинея' },
    { image: 'img/gr.png', country: 'Греция' },
    { image: 'img/gs.png', country: 'Южная Георгия и Южные Сандвичевы острова' },
    { image: 'img/gt.png', country: 'Гватемала' },
    { image: 'img/gu.png', country: 'Гуам' },
    { image: 'img/gw.png', country: 'Гвинея-Бисау' },
    { image: 'img/gy.png', country: 'Гайана' },
    { image: 'img/hk.png', country: 'Гонконг' },
    { image: 'img/hm.png', country: 'Остров Херд и острова Макдональд' },
    { image: 'img/hn.png', country: 'Гондурас' },
    { image: 'img/hr.png', country: 'Хорватия' },
    { image: 'img/ht.png', country: 'Гаити' },
    { image: 'img/hu.png', country: 'Венгрия' },
    { image: 'img/id.png', country: 'Индонезия' },
    { image: 'img/ie.png', country: 'Ирландия' },
    { image: 'img/il.png', country: 'Израиль' },
    { image: 'img/im.png', country: 'Остров Мэн' },
    { image: 'img/in.png', country: 'Индия' },
    { image: 'img/io.png', country: 'Британская территория в Индийском океане' },
    { image: 'img/iq.png', country: 'Ирак' },
    { image: 'img/ir.png', country: 'Иран' },
    { image: 'img/is.png', country: 'Исландия' },
    { image: 'img/it.png', country: 'Италия' },
    { image: 'img/je.png', country: 'Джерси' },
    { image: 'img/jm.png', country: 'Ямайка' },
    { image: 'img/jo.png', country: 'Иордания' },
    { image: 'img/jp.png', country: 'Япония' },
    { image: 'img/ke.png', country: 'Кения' },
    { image: 'img/kg.png', country: 'Киргизия' },
    { image: 'img/kh.png', country: 'Камбоджа' },
    { image: 'img/ki.png', country: 'Кирибати' },
    { image: 'img/km.png', country: 'Коморы' },
    { image: 'img/kn.png', country: 'Сент-Китс и Невис' },
    { image: 'img/kp.png', country: 'Северная Корея' },
    { image: 'img/kr.png', country: 'Южная Корея' },
    { image: 'img/kw.png', country: 'Кувейт' },
    { image: 'img/ky.png', country: 'Каймановы острова' },
    { image: 'img/kz.png', country: 'Казахстан' },
    { image: 'img/la.png', country: 'Лаос' },
    { image: 'img/lb.png', country: 'Ливан' },
    { image: 'img/lc.png', country: 'Сент-Люсия' },
    { image: 'img/li.png', country: 'Лихтенштейн' },
    { image: 'img/lk.png', country: 'Шри-Ланка' },
    { image: 'img/lr.png', country: 'Либерия' },
    { image: 'img/ls.png', country: 'Лесото' },
    { image: 'img/lt.png', country: 'Литва' },
    { image: 'img/lu.png', country: 'Люксембург' },
    { image: 'img/lv.png', country: 'Латвия' },
    { image: 'img/ly.png', country: 'Ливия' },
    { image: 'img/ma.png', country: 'Марокко' },
    { image: 'img/mc.png', country: 'Монако' },
    { image: 'img/md.png', country: 'Молдова' },
    { image: 'img/me.png', country: 'Черногория' },
    { image: 'img/mf.png', country: 'Сен-Мартен' },
    { image: 'img/mg.png', country: 'Мадагаскар' },
    { image: 'img/mh.png', country: 'Маршалловы Острова' },
    { image: 'img/mk.png', country: 'Северная Македония' },
    { image: 'img/ml.png', country: 'Мали' },
    { image: 'img/mm.png', country: 'Мьянма' },
    { image: 'img/mn.png', country: 'Монголия' },
    { image: 'img/mo.png', country: 'Макао' },
    { image: 'img/mp.png', country: 'Северные Марианские острова' },
    { image: 'img/mq.png', country: 'Мартиника' },
    { image: 'img/mr.png', country: 'Мавритания' },
    { image: 'img/ms.png', country: 'Монтсеррат' },
    { image: 'img/mt.png', country: 'Мальта' },
    { image: 'img/mu.png', country: 'Маврикий' },
    { image: 'img/mv.png', country: 'Мальдивы' },
    { image: 'img/mw.png', country: 'Малави' },
    { image: 'img/mx.png', country: 'Мексика' },
    { image: 'img/my.png', country: 'Малайзия' },
    { image: 'img/mz.png', country: 'Мозамбик' },
    { image: 'img/na.png', country: 'Намибия' },
    { image: 'img/nc.png', country: 'Новая Каледония' },
    { image: 'img/ne.png', country: 'Нигер' },
    { image: 'img/nf.png', country: 'Остров Норфолк' },
    { image: 'img/ng.png', country: 'Нигерия' },
    { image: 'img/ni.png', country: 'Никарагуа' },
    { image: 'img/nl.png', country: 'Нидерланды' },
    { image: 'img/no.png', country: 'Норвегия' },
    { image: 'img/np.png', country: 'Непал' },
    { image: 'img/nr.png', country: 'Науру' },
    { image: 'img/nu.png', country: 'Ниуэ' },
    { image: 'img/nz.png', country: 'Новая Зеландия' },
    { image: 'img/om.png', country: 'Оман' },
    { image: 'img/pa.png', country: 'Панама' },
    { image: 'img/pe.png', country: 'Перу' },
    { image: 'img/pf.png', country: 'Французская Полинезия' },
    { image: 'img/pg.png', country: 'Папуа - Новая Гвинея' },
    { image: 'img/ph.png', country: 'Филиппины' },
    { image: 'img/pk.png', country: 'Пакистан' },
    { image: 'img/pl.png', country: 'Польша' },
    { image: 'img/pm.png', country: 'Сен-Пьер и Микелон' },
    { image: 'img/pn.png', country: 'Питкэрн' },
    { image: 'img/pr.png', country: 'Пуэрто-Рико' },
    { image: 'img/ps.png', country: 'Палестина' },
    { image: 'img/pt.png', country: 'Португалия' },
    { image: 'img/pw.png', country: 'Палау' },
    { image: 'img/py.png', country: 'Парагвай' },
    { image: 'img/qa.png', country: 'Катар' },
    { image: 'img/re.png', country: 'Реюньон' },
    { image: 'img/ro.png', country: 'Румыния' },
    { image: 'img/rs.png', country: 'Сербия' },
    { image: 'img/ru.png', country: 'Святая Русь' },
    { image: 'img/rw.png', country: 'Руанда' },
    { image: 'img/sa.png', country: 'Саудовская Аравия' },
    { image: 'img/sb.png', country: 'Соломоновы Острова' },
    { image: 'img/sc.png', country: 'Сейшельские острова' },
    { image: 'img/sd.png', country: 'Судан' },
    { image: 'img/se.png', country: 'Швеция' },
    { image: 'img/sg.png', country: 'Сингапур' },
    { image: 'img/sh.png', country: 'Остров Святой Елены' },
    { image: 'img/si.png', country: 'Словения' },
    { image: 'img/sj.png', country: 'Шпицберген и Ян-Майен' },
    { image: 'img/sk.png', country: 'Словакия' },
    { image: 'img/sl.png', country: 'Сьерра-Леоне' },
    { image: 'img/sm.png', country: 'Сан-Марино' },
    { image: 'img/sn.png', country: 'Сенегал' },
    { image: 'img/so.png', country: 'Сомали' },
    { image: 'img/sr.png', country: 'Суринам' },
    { image: 'img/ss.png', country: 'Южный Судан' },
    { image: 'img/st.png', country: 'Сан-Томе и Принсипи' },
    { image: 'img/sv.png', country: 'Сальвадор' },
    { image: 'img/sx.png', country: 'Синт-Мартен' },
    { image: 'img/sy.png', country: 'Сирия' },
    { image: 'img/sz.png', country: 'Эсватини' },
    { image: 'img/tc.png', country: 'Теркс и Кайкос' },
    { image: 'img/td.png', country: 'Чад' },
    { image: 'img/tf.png', country: 'Французские Южные и Антарктические территории' },
    { image: 'img/tg.png', country: 'Того' },
    { image: 'img/th.png', country: 'Таиланд' },
    { image: 'img/tj.png', country: 'Таджикистан' },
    { image: 'img/tk.png', country: 'Токелау' },
    { image: 'img/tl.png', country: 'Восточный Тимор' },
    { image: 'img/tm.png', country: 'Туркмения' },
    { image: 'img/tn.png', country: 'Тунис' },
    { image: 'img/to.png', country: 'Тонга' },
    { image: 'img/tr.png', country: 'Турция' },
    { image: 'img/tt.png', country: 'Тринидад и Тобаго' },
    { image: 'img/tv.png', country: 'Тувалу' },
    { image: 'img/tw.png', country: 'Тайвань' },
    { image: 'img/tz.png', country: 'Танзания' },
    { image: 'img/ua.png', country: 'Да как-будто бы и не важно' },
    { image: 'img/ug.png', country: 'Уганда' },
    { image: 'img/um.png', country: 'Внешние малые острова США' },
    { image: 'img/us.png', country: 'Соединённые Штаты Америки' },
    { image: 'img/uy.png', country: 'Уругвай' },
    { image: 'img/uz.png', country: 'Узбекистан' },
    { image: 'img/va.png', country: 'Ватикан, по совместительству страна Олега' },
    { image: 'img/vc.png', country: 'Сент-Винсент и Гренадины' },
    { image: 'img/ve.png', country: 'Венесуэла' },
    { image: 'img/vg.png', country: 'Британские Виргинские острова' },
    { image: 'img/vi.png', country: 'Американские Виргинские острова' },
    { image: 'img/vn.png', country: 'Вьетнам' },
    { image: 'img/vu.png', country: 'Вануату' },
    { image: 'img/wf.png', country: 'Уоллис и Футуна' },
    { image: 'img/ws.png', country: 'Самоа' },
    { image: 'img/xk.png', country: 'Косово' },
    { image: 'img/ye.png', country: 'Йемен' },
    { image: 'img/yt.png', country: 'Майотта' },
    { image: 'img/za.png', country: 'Южно-Африканская Республика' },
    { image: 'img/zm.png', country: 'Замбия' },
    { image: 'img/zw.png', country: 'Зимбабве' }
        ];
    }

    currentIndex = getRandomInt(0, flags.length - 1);
    const flag = flags[currentIndex];

    const flagImage = document.getElementById('flagImage');
    flagImage.src = flag.image;
}

function showCountryName() {
    // Проверяем, был ли сгенерирован флаг
    if (currentIndex === null) {
        alert('Сначала сгенерируй флаг, тупица!');
        return;
    }

    const flag = flags[currentIndex];

    const randomColor = getRandomColor();

    const countryName = document.getElementById('countryName');
    countryName.textContent = flag.country;
    countryName.style.backgroundColor = randomColor;
    countryName.style.display = 'block';

    setTimeout(function() {
        countryName.style.display = 'none';
        colors.push(randomColor);
    }, 1000);
}
